# Generated by Django 3.1.7 on 2021-06-16 01:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='expires',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Expires'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authtoken',
            name='refresh_token',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=40, unique=True, verbose_name='Refresh_token'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.CharField(db_index=True, max_length=40, primary_key=True, serialize=False, verbose_name='Token'),
        ),
    ]
