# Generated by Django 3.1.7 on 2021-06-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210616_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expires',
            field=models.DateTimeField(verbose_name='Expires'),
        ),
    ]
