# Generated by Django 3.1.7 on 2021-06-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210616_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Token'),
        ),
    ]
